"""The prompts DCLab sends to a model, as versioned files (package A4.3).

Each ``<name>.md`` here is the system prompt of one agent or one model purpose; a module reads it with ``text(name)``
(placeholders such as ``${words}`` are filled from the module's own constants, so a number lives in one place).
Prompts are code: a person edits them, a test pins them. ``fingerprints()`` hashes every prompt file, every tool
scope's schemas and the workflow validator's rules; a complete scripted judgment suite run stores those hashes, and the test gate fails when a
prompt or a tool schema changed and the suite was not run again for it (``make agent-eval``). No model writes here.
"""

from __future__ import annotations

import functools
import hashlib
import json
from pathlib import Path
from string import Template
from typing import Any

HERE = Path(__file__).resolve().parent
TOOL_SCOPES = ("project", "draft", "session", "campaign")


@functools.cache
def _raw(name: str) -> str:
    text = (HERE / f"{name}.md").read_text(encoding="utf-8")
    return text[:-1] if text.endswith("\n") else text


def text(name: str, **values: Any) -> str:
    """The prompt ``name``, with its placeholders filled (every placeholder must be given; an unknown one is an error)."""
    raw = _raw(name)
    return Template(raw).substitute({k: str(v) for k, v in values.items()}) if values or "${" in raw else raw


def names() -> list[str]:
    return sorted(p.stem for p in HERE.glob("*.md"))


def fingerprints() -> dict[str, str]:
    """A short hash of every prompt file and of each tool scope's schemas (what a model is told it can call)."""
    from dclab_rnd.agents import default_registry

    out = {f"prompt:{n}": hashlib.sha256((HERE / f"{n}.md").read_bytes()).hexdigest()[:16] for n in names()}
    registry = default_registry()
    for scope in TOOL_SCOPES:
        schemas = [_stable(s) if scope == "campaign" else s for s in registry.schemas(scope)]
        out[f"tools:{scope}"] = hashlib.sha256(json.dumps(schemas, sort_keys=True, ensure_ascii=False).encode()).hexdigest()[:16]
    # the workflow validator's rules decide which moves pass: a change there needs the suite too
    out["validator:graph"] = hashlib.sha256((HERE.parent / "studio" / "graph.py").read_bytes()).hexdigest()[:16]
    return out


def _stable(schema: dict[str, Any]) -> dict[str, Any]:
    """A tool schema generated by a library (the campaign's experiment, from pydantic) varies with the library's
    version; its name, description, field names and required fields are what the model is told, and do not."""
    fn = schema.get("function", schema)
    params = fn.get("parameters") or {}
    return {"name": fn.get("name"), "description": fn.get("description"), "properties": sorted(params.get("properties") or {}),
            "required": sorted(params.get("required") or [])}
