"""Research lab and Benchmark: the R&D itself, read from the repository (read-only).

    GET /api/lab/summary     registry, champions, campaigns, critic gate, pitfalls, auditor headline,
                             research-track statuses and the campaign commands from the Makefile
    GET /api/lab/benchmark   blind auditor replay per dataset, the notebook pilot (when its frozen
                             manifest is committed) and the planned suites and policies, marked planned

Every number comes from a file or a deterministic function in the repository:

- registry and champions: ``registry.collect_registry`` + ``analysis.build_evidence``, the same
  code as ``python -m dclab_rnd status``;
- campaigns: ``evidence/campaigns/*/`` (manifest, immutable result JSONs, report);
- evidence index: ``evidence/knowledge/rag/records.jsonl`` (generated by ``make index``);
- critic gate: ``critic_gate.gate_campaigns`` + ``critic_gate.summary`` (``make critic-gate``);
- pitfalls: ``evidence/campaigns/pitfalls_v1/results/PIT-*.json``;
- blind auditor replay: the stored ``VER-001`` result written by ``make verify-auditor``;
- notebook pilot: ``notebook_assist_eval.evaluate`` on the frozen manifest at its committed home.

Results are cached by the modification times of the files they were read from.
"""

from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path
from typing import Any, Callable

from ... import research_map
from ..catalog import ROOT

CAMPAIGNS = ROOT / "evidence/campaigns"
RECORDS = ROOT / "evidence/knowledge/rag/records.jsonl"
VERIFY = CAMPAIGNS / "agent_verification_v1/results/VER-001_auditor_blind_replay.json"
PITFALLS = CAMPAIGNS / "pitfalls_v1/results"
RESEARCH = ROOT / "research"
MAKEFILE = ROOT / "Makefile"
REPORT_ORDER = ("CAMPAIGN_REPORT.md", "PITFALLS_REPORT.md", "VERIFICATION_REPORT.md")
# Makefile targets that run or inspect a campaign, in the order the designer lists them.
CAMPAIGN_TARGETS = ("pitfalls", "category-codes", "expansion", "verify-auditor", "rd-campaign-quick",
                    "rd-campaign-review", "critic-gate", "rd-campaign-status", "expansion-status",
                    "rd-campaign-verify", "new-track")
AFTER_RESULTS = ("rd-sync", "knowledge")

# The judgment benchmark is a plan from the product design (docs/product-demo); nothing below is a
# measurement. No suite case is frozen and no policy has been scored, so every item is "planned".
PLANNED_SUITES = (
    ("A", "Leakage traps", 30, "post-outcome columns, target encodings, duplicates, proxies"),
    ("B", "Split traps", 20, "time order, groups, resampling, fitted transforms"),
    ("C", "Metric and threshold", 15, "costs, imbalance, calibration"),
    ("D", "Stop and ask", 15, "only the owner can decide; guessing fails the case"),
    ("E", "Unseen projects", 40, "full ten-step runs on public notebooks never used in training"),
)
PLANNED_POLICIES = ("Standard plan (no model)", "General LLM (open model, router)",
                    "DCLab policy model", "Human reviewer")


# --------------------------------------------------------------------------- caching


_CACHE: dict[str, tuple[tuple, Any]] = {}


def _signature(paths: list[Path]) -> tuple:
    sig = []
    for path in paths:
        try:
            sig.append((str(path), path.stat().st_mtime_ns))
        except OSError:
            sig.append((str(path), None))
    return tuple(sig)


def _cached(key: str, paths: list[Path], compute: Callable[[], Any]) -> Any:
    """``compute()`` once per set of file modification times."""
    sig = _signature(paths)
    hit = _CACHE.get(key)
    if hit and hit[0] == sig:
        return hit[1]
    value = compute()
    _CACHE[key] = (sig, value)
    return value


def _rel(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)


def _read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


# --------------------------------------------------------------------------- registry and champions


def _registry_files() -> list[Path]:
    from ...registry import discover_result_files
    return discover_result_files(ROOT) + [ROOT / "evidence/knowledge/approved_baseline.json"]


def _registry() -> dict[str, Any]:
    """What ``python -m dclab_rnd status`` prints, as data."""
    from ...analysis import build_evidence
    from ...registry import collect_registry

    def compute():
        records, issues = collect_registry(ROOT)
        evidence = build_evidence(ROOT, records, issues)
        s = evidence["summary"]
        dataset_cards = {r["record_id"] for r in _index_records() if r.get("type") == "dataset"}
        champions = [{
            "dataset": c["dataset"], "family": c["model_family"], "recipe": c["experiment"], "model": c["model"],
            "metric": "ROC-AUC", "value": c["roc_auc"], "f1": c.get("f1"), "recall": c.get("recall"),
            "run_id": c["run_id"], "suite": c["suite"], "source": c["source_path"],
            "record": f"DATASET-{c['dataset']}" if f"DATASET-{c['dataset']}" in dataset_cards else None,
        } for c in evidence["champions"]]
        return {
            "registry": {
                "experiments": s["experiments"], "eligible": s["deployment_eligible_completed"],
                "datasets": s["datasets"], "suites": s["suites"], "status_counts": s["status_counts"],
                "with_provenance": s["with_provenance"], "result_files": len(records),
                "quality_errors": sum(1 for i in evidence["quality_issues"] if i.get("severity") == "error"),
                "regressions": len(evidence["regressions"]),
                "command": "python -m dclab_rnd status",
            },
            "champions": champions,
        }

    return _cached("registry", _registry_files() + [RECORDS], compute)


# --------------------------------------------------------------------------- evidence index


def _index_records() -> list[dict[str, Any]]:
    def compute():
        rows = []
        try:
            for line in RECORDS.read_text(encoding="utf-8").splitlines():
                if line.strip():
                    rows.append(json.loads(line))
        except (OSError, json.JSONDecodeError):
            return []
        return rows
    return _cached("records", [RECORDS], compute)


# --------------------------------------------------------------------------- campaigns


def _first_paragraph(text: str) -> tuple[str, str]:
    """(H1 title, first prose paragraph) of a Markdown report."""
    title, para = "", ""
    for block in re.split(r"\n\s*\n", text):
        block = block.strip()
        if not block:
            continue
        if block.startswith("# ") and not title:
            title = block[2:].splitlines()[0].strip()
            continue
        if block.startswith(("#", "|", "-", ">", "```")) or block.lower().startswith("status:"):
            continue
        para = " ".join(block.split())
        break
    return title, para


def _shorten(text: str, limit: int = 260) -> str:
    if len(text) <= limit:
        return text
    cut = text[:limit]
    end = max(cut.rfind(". "), cut.rfind("; "))
    return (cut[:end + 1] if end > 80 else cut.rstrip() + "…").strip()


def _datasets_of(result: dict[str, Any]) -> set[str]:
    names: set[str] = set()
    ds = result.get("dataset")
    if isinstance(ds, str) and ds != "multiple":
        names.add(ds)
    for item in result.get("datasets") if isinstance(result.get("datasets"), list) else []:
        if isinstance(item, str):
            names.add(item)
        elif isinstance(item, dict) and isinstance(item.get("dataset"), str):
            names.add(item["dataset"])
    for case in result.get("cases") or []:
        if isinstance(case, dict) and isinstance(case.get("dataset"), str):
            names.add(case["dataset"])
    return names


def _campaign_files() -> list[Path]:
    return sorted(p for p in CAMPAIGNS.glob("*/*") if p.is_file()) + sorted(CAMPAIGNS.glob("*/results/*.json"))


def _campaigns() -> list[dict[str, Any]]:
    def compute():
        index = _index_records()
        out = []
        for folder in sorted(p for p in CAMPAIGNS.iterdir() if p.is_dir()):
            results = [r for r in (_read_json(p) for p in sorted((folder / "results").glob("*.json"))) if isinstance(r, dict)]
            manifest = _read_json(folder / "manifest.json") or {}
            reports = [folder / n for n in REPORT_ORDER if (folder / n).is_file()] or sorted(folder.glob("*REPORT.md"))
            title, para = _first_paragraph(reports[0].read_text(encoding="utf-8")) if reports else ("", "")
            planned = manifest.get("experiment_count")
            if not isinstance(planned, int):
                planned = len(manifest["experiments"]) if isinstance(manifest.get("experiments"), list) else len(results)
            status_of = lambda r: r.get("status") or ("completed" if r.get("completed_at") else "unknown")  # noqa: E731
            completed = sum(status_of(r) == "completed" for r in results)
            failed = sum(status_of(r) == "failed" for r in results)
            datasets = sorted(set().union(*(_datasets_of(r) for r in results)) if results else set())
            if isinstance(manifest.get("datasets"), list):
                datasets = sorted(set(datasets) | {d for d in manifest["datasets"] if isinstance(d, str)})
            ids = [r.get("experiment_id") for r in results if r.get("experiment_id")]
            indexed = [r["record_id"] for r in index if (r.get("metadata") or {}).get("campaign") == folder.name]
            status = "failed" if failed else "done" if completed >= planned and results else "in progress" if results else "planned"
            dates = sorted(r.get("completed_at") for r in results if r.get("completed_at"))
            subtitle = title.split(":", 1)[1].strip() if ":" in title else ""
            objective = manifest.get("objective") or (f"{subtitle[:1].upper()}{subtitle[1:]}. {para}" if subtitle else para)
            out.append({
                "id": folder.name, "title": title, "objective": _shorten(objective),
                "experiments": len(results), "planned": planned, "completed": completed, "failed": failed,
                "status": status, "datasets": datasets, "record_ids": ids, "index_records": len(indexed),
                "report": _rel(reports[0]) if reports else None, "last_completed_at": dates[-1] if dates else None,
                "extends": manifest.get("extends"), "rule": manifest.get("rule"),
            })
        return out
    return _cached("campaigns", _campaign_files() + [RECORDS], compute)


# --------------------------------------------------------------------------- critic gate


def _critic() -> dict[str, Any]:
    from ... import critic_gate

    def compute():
        gated = critic_gate.gate_campaigns(ROOT)
        stats = critic_gate.summary(gated)
        examples = []
        for g in gated:
            check = g.get("rule_check") or {}
            for c in g["challenges"]:
                if c["gate"] == "contradicted":
                    examples.append({
                        "experiment_id": g["experiment_id"], "dataset": g["dataset"], "kind": g["kind"],
                        "claim_id": c.get("claim_id"), "severity": c.get("severity"), "issue": c.get("issue", ""),
                        "rule": check.get("rule"), "metric": check.get("metric"), "recorded": check.get("recorded"),
                        "recomputed": check.get("recomputed"), "consistent": check.get("consistent"),
                        "eligible": check.get("eligible"), "path": g.get("path"),
                    })
        examples.sort(key=lambda e: e["experiment_id"] or "")
        return {
            "experiments": stats["experiments"], "recomputable_rules": stats["recomputable_rules"],
            "rule_inconsistencies": stats["rule_inconsistencies"], "challenges": stats["critic_challenges"],
            "contradicted": stats["contradicted_challenges"],
            "kept": stats["critic_challenges"] - stats["contradicted_challenges"],
            "experiments_with_contradicted": stats["experiments_with_contradicted_challenges"],
            "examples": examples, "command": "make critic-gate",
        }
    return _cached("critic", sorted(CAMPAIGNS.glob("*/results/EXP-*.json")), compute)


# --------------------------------------------------------------------------- pitfalls


def _first_sentence(text: str) -> str:
    m = re.match(r"(.+?[.!?])(\s|$)", text or "")
    return m.group(1) if m else (text or "")


def _pitfall_cost(result: dict[str, Any]) -> dict[str, Any]:
    """The measured cost of one pitfall, from its own evidence (no typed numbers)."""
    ev = result.get("evidence") or {}
    rows = [r for r in ev.get("datasets") or [] if isinstance(r, dict)]
    with_inflation = [r for r in rows if isinstance(r.get("inflation"), dict)]
    if with_inflation:
        worst = max(with_inflation, key=lambda r: abs(r["inflation"]["mean"]))
        value = worst["inflation"]["mean"]
        return {"value": value, "text": f"{'up to ' if len(with_inflation) > 1 else ''}{value:+.4f} ROC-AUC",
                "detail": f"{worst['dataset']}: {worst['wrong_auc']['mean']:.4f} reported, {worst['right_auc']['mean']:.4f} honest",
                "dataset": worst["dataset"]}
    with_bias = [r for r in rows if isinstance(r.get("selection_bias"), dict)]
    if with_bias and isinstance(ev.get("average_selection_bias"), (int, float)):
        worst = max(with_bias, key=lambda r: r["selection_bias"]["mean"])
        avg = ev["average_selection_bias"]
        rank = ev.get("average_rank_of_pick_on_untouched_holdout")
        configs = worst.get("configs")
        detail = f"max {worst['selection_bias']['mean']:+.4f} on {worst['dataset']}"
        if isinstance(rank, (int, float)) and configs:
            detail += f"; the pick ranked {rank:.1f} of {configs} on untouched data"
        return {"value": avg, "text": f"{avg:+.4f} ROC-AUC on average", "detail": detail, "dataset": worst["dataset"]}
    if isinstance(ev.get("optimism_gap"), (int, float)):
        gap = ev["optimism_gap"]
        rnd = (ev.get("random_split_auc") or {}).get("mean") if isinstance(ev.get("random_split_auc"), dict) else ev.get("random_split_auc")
        fwd = ev.get("time_ordered_auc")
        names = result.get("datasets") or []
        detail = f"random split {rnd:.4f} vs forward in time {fwd:.4f}" if isinstance(rnd, (int, float)) and isinstance(fwd, (int, float)) else ""
        if names:
            detail += f" ({', '.join(names)})"
        return {"value": gap, "text": f"{gap:+.4f} ROC-AUC", "detail": detail, "dataset": names[0] if names else None}
    return {"value": None, "text": "", "detail": "", "dataset": None}


def _pitfalls() -> list[dict[str, Any]]:
    def compute():
        titles = {r["record_id"]: r.get("title") for r in _index_records() if r.get("type") == "pitfall"}
        out = []
        for path in sorted(PITFALLS.glob("PIT-*.json")):
            r = _read_json(path)
            if not isinstance(r, dict):
                continue
            claims = r.get("claims") or []
            fact = next((c for c in claims if c.get("kind") == "fact"), None)
            rec = next((c for c in claims if c.get("kind") == "recommendation"), None)
            name = re.sub(r"\bcv\b", "CV", str(r.get("pitfall") or "").replace("_", " "))
            out.append({
                "id": r.get("experiment_id"), "pitfall": r.get("pitfall"), "name": name[:1].upper() + name[1:],
                "title": titles.get(r.get("experiment_id")), "question": r.get("question"),
                "cost": _pitfall_cost(r), "finding": fact.get("statement") if fact else None,
                "lesson": _first_sentence(rec.get("statement")) if rec else None,
                "limitations": (fact or rec or {}).get("limitations") or [],
                "datasets": r.get("datasets") or [], "indexed": r.get("experiment_id") in titles, "path": _rel(path),
            })
        return out
    return _cached("pitfalls", sorted(PITFALLS.glob("PIT-*.json")) + [RECORDS], compute)


# --------------------------------------------------------------------------- blind auditor replay


def _auditor(detail: bool = False) -> dict[str, Any] | None:
    def compute():
        r = _read_json(VERIFY)
        if not isinstance(r, dict):
            return None
        cases = [{"dataset": c.get("dataset"), "known": c.get("known_leaks") or [], "found": c.get("found") or [],
                  "missed": c.get("missed") or [], "false_alarms": c.get("false_alarms") or [],
                  "recall": c.get("recall"), "flagged": c.get("flagged_total")} for c in r.get("cases") or []]
        report = VERIFY.parent.parent / "VERIFICATION_REPORT.md"
        return {
            "id": r.get("experiment_id"), "campaign": r.get("campaign_id"), "question": r.get("question"),
            "known": r.get("known_leaks"), "found": r.get("found"), "recall": r.get("recall"),
            "datasets": r.get("datasets"), "datasets_all_found": r.get("datasets_with_every_leak_found"),
            "datasets_any_found": r.get("datasets_with_at_least_one_leak_found"),
            "false_alarms": sum(len(c["false_alarms"]) for c in cases),
            "completed_at": r.get("completed_at"), "path": _rel(VERIFY),
            "report": _rel(report) if report.is_file() else None, "command": "make verify-auditor", "cases": cases,
        }
    value = _cached("auditor", [VERIFY], compute)
    if value is None or detail:
        return value
    return {k: v for k, v in value.items() if k != "cases"}


# --------------------------------------------------------------------------- notebook pilot


def _notebook_pilot() -> dict[str, Any]:
    from ...notebook_assist import MANIFEST_CANDIDATES
    manifest = MANIFEST_CANDIDATES[0]  # the committed home; the other candidate is a pre-reorganization path
    base = {"manifest": _rel(manifest), "command": f".venv/bin/python -m dclab_rnd.notebook_assist_eval --manifest {_rel(manifest)} --output <new file>"}
    if not manifest.is_file():
        return {**base, "status": "not_committed",
                "note": "The frozen pilot manifest is not committed, so the pilot cannot be scored from the repository "
                        "(tests/test_notebook_eval.py skips for the same reason)."}

    def compute():
        from ...notebook_assist_eval import evaluate
        try:
            cases = json.loads(manifest.read_text(encoding="utf-8"))
            report = evaluate(cases)
        except Exception as exc:  # a changed cell or a missing notebook: report it, never guess a score
            return {**base, "status": "error", "note": str(exc)}
        why = {c.get("id"): c.get("why") for c in cases.get("cases", [])}
        signal = {c.get("id"): c.get("signal") for c in cases.get("cases", [])}
        return {**base, "status": "scored", "suite_id": report.get("suite_id"), "scope": report.get("scope"),
                "passed": report["cases_passed"], "total": report["cases_total"],
                "proof_rules_passed": report["proof_rules_passed"], "proof_rules_scored": report["proof_rules_scored"],
                "availability_wording_safe": report["availability_wording_safe"],
                "cases": [{"id": r["id"], "signal": signal.get(r["id"]), "expected": r["expected"], "observed": r["observed"],
                           "pass": r["pass"], "proof_rule_pass": r.get("proof_rule_pass"), "why": why.get(r["id"])}
                          for r in report["records"]]}
    return _cached("pilot", [manifest], compute)


# --------------------------------------------------------------------------- research tracks and commands




def _track_status() -> dict[str, dict[str, str]]:
    readmes = sorted(p for p in RESEARCH.glob("*/README.md") if not p.parent.name.startswith("_"))

    def compute():
        out = {}
        for path in readmes:
            text = research_map.readme_status(path.read_text(encoding="utf-8"))  # the same reading as the research map
            low = text.lower()
            kind = ("active" if low.startswith("active") else "planned" if low.startswith("planned")
                    else "concluded" if low.startswith("concluded") else "paused" if low.startswith("paused")
                    else "proposed" if re.search(r"propos|hypothesis", low) else "open" if text else "unknown")
            note = text.split(" · ", 1)[1] if " · " in text else ("" if low == kind else text)
            note = re.sub(r"^proposed( research)?[;,]?\s*", "", note) if kind == "proposed" else note
            out[path.parent.name] = {"kind": kind, "text": text, "note": note.replace("`", "")}
        return out
    return _cached("tracks", readmes, compute)


def _commands() -> dict[str, list[dict[str, str]]]:
    def compute():
        try:
            lines = MAKEFILE.read_text(encoding="utf-8").splitlines()
        except OSError:
            return {"campaign": [], "after": []}
        python = next((m.group(1).strip() for m in (re.match(r"PYTHON\s*\?=\s*(.+)", l) for l in lines) if m), "python")
        targets = {}
        for i, line in enumerate(lines):
            m = re.match(r"^([a-z0-9-]+):([^=#]*)##\s*(.+)$", line)
            if not m:
                continue
            recipe = []
            for nxt in lines[i + 1:]:
                if not nxt.startswith("\t"):
                    break
                recipe.append(nxt.strip().lstrip("@").replace("$(PYTHON)", python))
            runs = " && ".join(recipe) or ("make " + " ".join(m.group(2).split()) if m.group(2).strip() else "")
            targets[m.group(1)] = {"target": m.group(1), "help": m.group(3).strip(),
                                   "runs": "" if "$(" in runs else runs, "command": f"make {m.group(1)}"}
        if "new-track" in targets:
            targets["new-track"]["command"] = 'make new-track NAME=... TITLE="..." PREFIX=...'
        return {"campaign": [targets[t] for t in CAMPAIGN_TARGETS if t in targets],
                "after": [targets[t] for t in AFTER_RESULTS if t in targets]}
    return _cached("commands", [MAKEFILE], compute)


# --------------------------------------------------------------------------- payloads


def lab_summary() -> dict[str, Any]:
    reg = _registry()
    campaigns = _campaigns()
    index = _index_records()
    return {
        "registry": reg["registry"], "champions": reg["champions"], "campaigns": campaigns,
        "index": {"records": len(index), "campaign_records": sum(c["index_records"] for c in campaigns),
                  "source": _rel(RECORDS)},
        "critic": _critic(), "pitfalls": _pitfalls(), "auditor": _auditor(),
        "track_status": _track_status(), "commands": _commands(),
    }


def lab_benchmark() -> dict[str, Any]:
    suites = [{"id": i, "name": n, "planned_cases": k, "covers": c, "status": "planned", "scored_cases": 0}
              for i, n, k, c in PLANNED_SUITES]
    return {
        "auditor": _auditor(detail=True),
        "notebook_pilot": _notebook_pilot(),
        "suites": {"status": "planned", "planned_cases": sum(s["planned_cases"] for s in suites), "items": suites,
                   "note": "A plan from the product design; no case is frozen yet."},
        "policies": {"status": "planned", "scored": 0,
                     "items": [{"name": p, "status": "planned", "scores": None} for p in PLANNED_POLICIES],
                     "note": "Planned — no policy scored yet."},
    }


def register(app, ctx) -> None:
    @app.get("/api/lab/summary")
    async def lab_summary_route():
        """The registry, champions, campaigns, critic gate, pitfalls and auditor headline, from the repository."""
        return await asyncio.to_thread(lab_summary)

    @app.get("/api/lab/benchmark")
    async def lab_benchmark_route():
        """The measured pilots (blind auditor replay, notebook pilot) and the planned suites, marked planned."""
        return await asyncio.to_thread(lab_benchmark)
