"""Export a finished project as a runnable notebook and a report.

The notebook reproduces the approved workflow with plain scikit-learn code so an
engineer can take it anywhere: the same contract, split, recipe, model and
parameters, and the same once-only holdout.
"""

from __future__ import annotations

import json
from typing import Any

from .store import STAGE_KEYS

MODEL_IMPORTS = {
    "logistic_regression": ("from sklearn.linear_model import LogisticRegression", "LogisticRegression(C=1.0, max_iter=3000)"),
    "ridge": ("from sklearn.linear_model import Ridge", "Ridge(alpha=1.0)"),
    "linear_svm": ("from sklearn.svm import LinearSVC", "LinearSVC(C=0.1, max_iter=5000, random_state=42)"),
    "complement_nb": ("from sklearn.naive_bayes import ComplementNB", "ComplementNB(alpha=1.0)"),
    "extra_trees": ("from sklearn.ensemble import ExtraTreesClassifier, ExtraTreesRegressor", "{cls}(n_estimators=300, min_samples_leaf=2, n_jobs=4, random_state=42)"),
    "hist_gradient_boosting": ("from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor", "{cls}(random_state=42)"),
    "lightgbm": ("import lightgbm as lgb", "lgb.{cls}(n_estimators=300, learning_rate=0.05, num_leaves=31, random_state=42, n_jobs=4, verbose=-1)"),
    "xgboost": ("import xgboost as xgb", "xgb.{cls}(n_estimators=300, learning_rate=0.1, max_depth=6, tree_method='hist', n_jobs=4, random_state=42, verbosity=0)"),
}
CLASS_NAMES = {
    "extra_trees": ("ExtraTreesClassifier", "ExtraTreesRegressor"),
    "hist_gradient_boosting": ("HistGradientBoostingClassifier", "HistGradientBoostingRegressor"),
    "lightgbm": ("LGBMClassifier", "LGBMRegressor"),
    "xgboost": ("XGBClassifier", "XGBRegressor"),
}
METRIC_CODE = {
    "roc_auc": ("roc_auc_score", "roc_auc_score(y_true, scores)"),
    "average_precision": ("average_precision_score", "average_precision_score(y_true, scores)"),
    "macro_f1": ("f1_score", "f1_score(y_true, scores.argmax(axis=1), average='macro')"),
    "mae": ("mean_absolute_error", "mean_absolute_error(y_true, scores)"),
}


def _cell(kind: str, source: str) -> dict[str, Any]:
    cell = {"cell_type": kind, "metadata": {}, "source": source.rstrip("\n") + "\n"}
    if kind == "code":
        cell.update(execution_count=None, outputs=[])
    return cell


def notebook(project: dict[str, Any], records: dict[str, dict[str, Any]]) -> dict[str, Any]:
    contract = project["contract"] or {}
    data = project["data"] or {}
    task = contract.get("task", "binary")
    regression = task == "regression"
    features = records.get("features", {}).get("decision", {})
    models = records.get("models", {}).get("decision", {})
    final = records.get("final", {}).get("evidence", {})
    recipe = features.get("chosen") or features.get("selected") or "raw"
    family = models.get("chosen") or models.get("selected") or ("ridge" if regression else "logistic_regression")
    params = {k.replace("model__", ""): v for k, v in (final.get("selected_model_params") or {}).items()}
    metric = records.get("final", records.get("features", {})).get("primary_metric") or ("mae" if regression else "roc_auc")
    forbidden = [f["column"] for f in contract.get("forbidden", [])]
    identifiers = list(contract.get("identifiers", []))
    time_column, group_column = contract.get("time_column"), contract.get("group_column")
    drop = sorted(set(forbidden + identifiers + ([time_column] if time_column else []) + ([group_column] if group_column else []) + list(contract.get("text_columns", []))))
    import_line, ctor = MODEL_IMPORTS[family]
    cls = CLASS_NAMES.get(family, ("", ""))[1 if regression else 0]
    ctor = ctor.format(cls=cls)
    metric_import, metric_expr = METRIC_CODE[metric]

    cells = [
        _cell("markdown", f"# {project['name']}\n\n"
              f"**Goal.** {project.get('goal') or '—'}\n\n"
              f"**Prediction contract.** Target `{contract.get('target')}` ({task}). {contract.get('prediction_moment', '')}\n\n"
              + (f"**Forbidden at prediction time:** " + ", ".join(f"`{c}`" for c in forbidden) + "\n\n" if forbidden else "")
              + (f"**Identifiers (never features):** " + ", ".join(f"`{c}`" for c in identifiers) + "\n\n" if identifiers else "")
              + f"**Metric.** {metric}\n\n"
              "Generated by the DCLab notebook. Every split, metric and selection rule below reproduces the project's approved workflow; "
              "the holdout is scored once, at the end. Scores are evidence about the method, not production approval."),
        _cell("code", "import numpy as np\nimport pandas as pd\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.impute import SimpleImputer\n"
              "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import OneHotEncoder, StandardScaler\n"
              f"from sklearn.metrics import {metric_import}\n{import_line}\n\nRANDOM_STATE = 42"),
        _cell("markdown", "## 1. Load the data and apply the contract\n\nColumns unknown at the prediction moment and identifiers are removed before anything else happens."),
        _cell("code", f"frame = pd.read_csv({data.get('filename', 'data.csv')!r})  # the project's data file\n"
              f"TARGET = {contract.get('target')!r}\nDROP = {drop!r}\n"
              + _target_code(task, contract)
              + f"X = frame.drop(columns=[TARGET] + [c for c in DROP if c in frame])\nprint(X.shape, y.value_counts(normalize=True).round(3).to_dict() if y.nunique() < 20 else y.describe())"),
        _cell("markdown", "## 2. Lock the holdout before looking at the target\n\n" + _split_text(time_column, group_column, regression)),
        _cell("code", _split_code(time_column, group_column, regression, data)),
        _cell("markdown", f"## 3. Feature recipe `{recipe}`\n\n{features.get('rule', '')}\n\nEvery statistic (imputation, scaling, one-hot categories) is learned inside the training folds only."),
        _cell("code", _recipe_code(recipe, time_column)),
        _cell("markdown", f"## 4. Model `{family}`\n\n{models.get('rule', '')}\n\n"
              + (f"Tuned parameters accepted: `{params}`" if params else "Default parameters kept (tuning did not beat them by the required margin).")),
        _cell("code", f"model = {ctor}\n" + (f"model.set_params(**{params!r})\n" if params else "") + "pipeline = Pipeline([('features', features), ('model', model)])"),
        _cell("markdown", "## 5. Training-only cross-validation\n\nThe same folds for every comparison; the holdout is still sealed."),
        _cell("code", _cv_code(task, metric_expr, regression)),
        _cell("markdown", "## 6. Score the holdout once\n\nThis is the honest number. Changing the model after seeing it would make the next score optimistic (DCLAB-R17)."),
        _cell("code", "pipeline.fit(X_train, y_train)\n" + _score_code(task, metric_expr) + "print('holdout', round(float(holdout), 4))"),
        _cell("markdown", _result_markdown(records, metric)),
    ]
    return {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                                        "language_info": {"name": "python"}, "dclab": {"project": project["id"], "generated_from": "DCLab notebook"}},
            "nbformat": 4, "nbformat_minor": 5}


def _target_code(task: str, contract: dict[str, Any]) -> str:
    if task == "binary":
        return f"y = (frame[TARGET].astype(str).str.strip() == {str(contract.get('positive_label'))!r}).astype(int)\n"
    if task == "multiclass":
        return "labels = sorted(frame[TARGET].dropna().astype(str).unique())\ny = frame[TARGET].astype(str).map({l: i for i, l in enumerate(labels)}).astype(int)\n"
    return "y = pd.to_numeric(frame[TARGET], errors='coerce')\nframe = frame[y.notna()].reset_index(drop=True)\ny = y[y.notna()].reset_index(drop=True)\n"


def _split_text(time_column: str | None, group_column: str | None, regression: bool) -> str:
    if time_column:
        return f"Rows are ordered by `{time_column}`; the last 20% form the holdout and the folds expand forward in time, so nothing learns from the future."
    if group_column:
        return f"Rows that share a `{group_column}` stay on the same side of every split, so the model is scored on groups it never saw."
    return "A random holdout" + ("" if regression else ", stratified on the target") + ", with the training folds drawn only from the remaining rows."


def _split_code(time_column: str | None, group_column: str | None, regression: bool, data: dict[str, Any]) -> str:
    if time_column:
        return (f"order = np.argsort(pd.to_datetime(frame[{time_column!r}], errors='coerce').to_numpy().astype('int64') if frame[{time_column!r}].dtype == object else frame[{time_column!r}].to_numpy(), kind='stable')\n"
                "X, y = X.iloc[order].reset_index(drop=True), y.iloc[order].reset_index(drop=True)\n"
                "n_test = int(round(0.2 * len(X)))\nX_train, X_test = X.iloc[:-n_test], X.iloc[-n_test:]\ny_train, y_test = y.iloc[:-n_test], y.iloc[-n_test:]\n"
                "from sklearn.model_selection import TimeSeriesSplit\ncv = TimeSeriesSplit(n_splits=3)\ncv_groups = None")
    if group_column:
        kf = "GroupKFold" if regression else "StratifiedGroupKFold"
        return (f"from sklearn.model_selection import {kf}\ngroups = frame[{group_column!r}].to_numpy()\n"
                f"train_idx, test_idx = next({kf}(n_splits=5{'' if regression else ', shuffle=True, random_state=RANDOM_STATE'}).split(X, y, groups))\n"
                "X_train, X_test, y_train, y_test = X.iloc[train_idx], X.iloc[test_idx], y.iloc[train_idx], y.iloc[test_idx]\n"
                f"cv = {kf}(n_splits=3{'' if regression else ', shuffle=True, random_state=RANDOM_STATE'})\ncv_groups = groups[train_idx]")
    kf = "KFold" if regression else "StratifiedKFold"
    return (f"from sklearn.model_selection import train_test_split, {kf}\n"
            f"X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, {'' if regression else 'stratify=y, '}random_state=RANDOM_STATE)\n"
            f"cv = {kf}(n_splits=3, shuffle=True, random_state=RANDOM_STATE)\ncv_groups = None")


def _recipe_code(recipe: str, time_column: str | None) -> str:
    derived = ""
    if recipe in ("log_numeric",):
        derived = ("from sklearn.preprocessing import FunctionTransformer\n"
                   "def add_logs(df):\n    df = df.copy()\n    for c in df.select_dtypes('number').columns:\n        if df[c].nunique() > 2:\n            df[f'log_{c}'] = np.sign(df[c]) * np.log1p(df[c].abs())\n    return df\n")
    if recipe == "calendar" and time_column:
        derived = ("from sklearn.preprocessing import FunctionTransformer\n"
                   f"def add_calendar(df):\n    df = df.copy()\n    stamp = pd.to_datetime(frame.loc[df.index, {time_column!r}], errors='coerce')\n"
                   "    doy = stamp.dt.dayofyear.astype(float)\n    df['doy_sin'], df['doy_cos'] = np.sin(2 * np.pi * doy / 365.25), np.cos(2 * np.pi * doy / 365.25)\n"
                   "    df['day_of_month'], df['week_of_year'], df['is_weekend'] = stamp.dt.day, stamp.dt.isocalendar().week.astype(float).to_numpy(), (stamp.dt.dayofweek >= 5).astype(float)\n    return df\n")
    if recipe == "poly2":
        derived = ("from sklearn.preprocessing import FunctionTransformer\n"
                   "def add_products(df):\n    df = df.copy()\n    cols = [c for c in df.select_dtypes('number').columns if df[c].nunique() > 2]\n"
                   "    for i, a in enumerate(cols):\n        for b in cols[i + 1:]:\n            df[f'{a}*{b}'] = df[a] * df[b]\n    return df\n")
    pre = ("numeric = X_train.select_dtypes('number').columns.tolist()\ncategorical = [c for c in X_train.columns if c not in numeric]\n"
           "preprocess = ColumnTransformer([\n    ('numeric', Pipeline([('impute', SimpleImputer(strategy='median')), ('scale', StandardScaler())]), numeric),\n"
           "    ('categorical', Pipeline([('impute', SimpleImputer(strategy='constant', fill_value='missing')), ('onehot', OneHotEncoder(handle_unknown='ignore', max_categories=40))]), categorical),\n], remainder='drop')\n")
    if recipe == "selected_mi":
        return (pre + "from sklearn.feature_selection import SelectKBest, mutual_info_classif\n"
                "features = Pipeline([('preprocess', preprocess), ('select', SelectKBest(mutual_info_classif, k=min(20, len(numeric) + len(categorical))))])")
    if derived:
        fn = {"log_numeric": "add_logs", "calendar": "add_calendar", "poly2": "add_products"}[recipe]
        return derived + "\n" + pre.replace("X_train.select_dtypes", f"{fn}(X_train).select_dtypes").replace("X_train.columns", f"{fn}(X_train).columns") + \
            f"features = Pipeline([('derive', FunctionTransformer({fn})), ('preprocess', preprocess)])"
    return pre + "features = preprocess"


def _cv_code(task: str, metric_expr: str, regression: bool) -> str:
    score = "pipeline.predict(X_valid)" if regression else ("pipeline.predict_proba(X_valid)" if task == "multiclass" else "pipeline.predict_proba(X_valid)[:, 1]")
    return ("fold_scores = []\nfor fit_idx, valid_idx in cv.split(X_train, y_train, cv_groups) if cv_groups is not None else cv.split(X_train, y_train):\n"
            "    pipeline.fit(X_train.iloc[fit_idx], y_train.iloc[fit_idx])\n    X_valid, y_true = X_train.iloc[valid_idx], y_train.iloc[valid_idx]\n"
            f"    scores = {score}\n    fold_scores.append({metric_expr})\n"
            "print('CV mean', round(float(np.mean(fold_scores)), 4), 'std', round(float(np.std(fold_scores, ddof=1)), 4))")


def _score_code(task: str, metric_expr: str) -> str:
    score = "pipeline.predict(X_test)" if task == "regression" else ("pipeline.predict_proba(X_test)" if task == "multiclass" else "pipeline.predict_proba(X_test)[:, 1]")
    return f"scores, y_true = {score}, y_test\nholdout = {metric_expr}\n"


def _result_markdown(records: dict[str, dict[str, Any]], metric: str) -> str:
    lines = ["## What the DCLab notebook found", ""]
    for stage in STAGE_KEYS:
        record = records.get(stage)
        if not record:
            continue
        lines.append(f"**{record['title']}.** {record['setup_summary']}")
        for note in record.get("notes", [])[:3]:
            if note["severity"] != "info":
                lines.append(f"- *{note['title']}* — {note['text']} (proof: {', '.join(note['proof'])})")
        lines.append("")
    final = records.get("final", {}).get("evidence")
    if final:
        ci = final["holdout_primary_metric_ci"]
        lines.append(f"Holdout {metric}: **{final['holdout_metrics'][metric]:.4f}** (95% {ci['low']:.4f}–{ci['high']:.4f}); the holdout was consumed {final.get('holdout_uses_in_this_project', 1)} time(s). Not production-approved.")
    return "\n".join(lines)


def report(project: dict[str, Any], records: dict[str, dict[str, Any]]) -> str:
    contract = project.get("contract") or {}
    lines = [f"# {project['name']}", "", f"*Industry:* {project.get('industry', 'general')} · *Created:* {project.get('created', '')[:10]}", "",
             f"**Goal.** {project.get('goal') or '—'}", "",
             "## Prediction contract", "",
             f"| Item | Value |", "|---|---|", f"| Target | `{contract.get('target')}` ({contract.get('task')}) |",
             f"| Prediction moment | {contract.get('prediction_moment', '')} |",
             f"| Forbidden columns | {', '.join('`' + f['column'] + '`' for f in contract.get('forbidden', [])) or 'none'} |",
             f"| Identifiers | {', '.join('`' + c + '`' for c in contract.get('identifiers', [])) or 'none'} |",
             f"| Time / group column | {contract.get('time_column') or '—'} / {contract.get('group_column') or '—'} |",
             f"| Metric | {contract.get('metric') or 'default for the task'} |", ""]
    for index, stage in enumerate(STAGE_KEYS, 1):
        record = records.get(stage)
        if not record:
            continue
        lines += [f"## {index}. {record['title']}", "", f"*{record['question']}*", "", record["setup_summary"], ""]
        for claim in record["claims"]:
            lines.append(f"- **{claim['kind']}** — {claim['statement']}")
            for limit in claim.get("limitations", []):
                lines.append(f"  - limitation: {limit}")
        decision = record.get("decision")
        if decision and decision.get("options"):
            lines += ["", f"Decision: `{decision['chosen']}`" + (" (chosen by the person; the rule selected `" + decision["selected"] + "`)" if decision.get("overridden") else " (by the selection rule)"), ""]
        lines += ["", "Agent notes:", ""]
        for note in record.get("notes", []):
            lines.append(f"- [{note['severity']}] **{note['title']}** — {note['text']} _(proof: {', '.join(note['proof']) or '—'})_")
        lines.append("")
    lines += ["---", "", "Generated by the DCLab notebook. Research evidence is not production approval (DCLAB-R22)."]
    return "\n".join(lines)


def dumps_notebook(nb: dict[str, Any]) -> str:
    return json.dumps(nb, indent=1, ensure_ascii=False)
